name: CI workflow

on: [push]

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    steps:

      # Put the repository in the virtual machine
      - name: Checkout
        uses: actions/checkout@v3

      # Install node in the virtual machine
      - name: Use Node.js
        uses: actions/setup-node@v3

      - run: npm install
      - run: npm run lint
      - run: npm test